services:
  payload:
    image: node:20-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - media:/home/node/app/media
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crtib
      POSTGRES_DB: crtib_cms
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  pgdata:
  node_modules:
  media: