[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["openssl"]

[phases.install]
cmds = ["corepack enable && corepack prepare pnpm@latest --activate && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "npx payload migrate && pnpm start"
