/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    news: News;
    partners: Partner;
    videos: Video;
    'activity-reports': ActivityReport;
    'timeline-items': TimelineItem;
    clauses: Clause;
    'newsletter-subscribers': NewsletterSubscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'activity-reports': ActivityReportsSelect<false> | ActivityReportsSelect<true>;
    'timeline-items': TimelineItemsSelect<false> | TimelineItemsSelect<true>;
    clauses: ClausesSelect<false> | ClausesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage users and access permissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and documents uploaded to the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Website pages, organized in a menu hierarchy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Friendly URL for the page (e.g. our-history)
   */
  slug: string;
  /**
   * Leave blank if it is a root page
   */
  parent?: (number | null) | Page;
  /**
   * Position in the menu (lowest number appears first)
   */
  menuOrder?: number | null;
  /**
   * Icon displayed next to the title in the navigation menu
   */
  icon?:
    | (
        | 'user'
        | 'document'
        | 'globe'
        | 'leaf'
        | 'calendar'
        | 'building'
        | 'book'
        | 'graduation'
        | 'external-link'
        | 'star'
        | 'settings'
        | 'list'
      )
    | null;
  /**
   * Page builder: add, order, and configure each section.
   */
  layout?:
    | (
        | {
            slides?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  eyebrow?: string | null;
                  title: string;
                  id?: string | null;
                }[]
              | null;
            autoPlayMs?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoHeroCarousel';
          }
        | {
            title?: string | null;
            maxItems?: number | null;
            variant?: ('default' | 'block') | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsSection';
          }
        | {
            title?: string | null;
            items?:
              | {
                  type: 'pdf' | 'video';
                  title: string;
                  triggerLabel?: string | null;
                  file?: (number | null) | Media;
                  videoUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'documentsSection';
          }
        | {
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calculator';
          }
        | {
            title?: string | null;
            clauses: (number | Clause)[];
            redirectLabel?: string | null;
            redirectHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'clausesGrid';
          }
        | {
            title?: string | null;
            columns?:
              | {
                  id: string;
                  label: string;
                  type: 'text' | 'number' | 'percentage' | 'date';
                  precision?: number | null;
                  currency?: string | null;
                }[]
              | null;
            rows?:
              | {
                  values:
                    | {
                        [k: string]: unknown;
                      }
                    | unknown[]
                    | string
                    | number
                    | boolean
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamicGrid';
          }
        | {
            documents?:
              | {
                  numero: string;
                  titulo: string;
                  data: string;
                  versao?: string | null;
                  pdf?: (number | null) | Media;
                  rtf?: (number | null) | Media;
                  doc?: (number | null) | Media;
                  xls?: (number | null) | Media;
                  zip?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            pageSize?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'downloadGrid';
          }
        | {
            title?: string | null;
            items?:
              | {
                  label: string;
                  file?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'downloadLinks';
          }
        | {
            items?:
              | {
                  title: string;
                  href: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quickLinks';
          }
        | {
            root: {
              name: string;
              role?: string | null;
              photo?: (number | null) | Media;
              children?:
                | {
                    name: string;
                    role?: string | null;
                    photo?: (number | null) | Media;
                    children?:
                      | {
                          name: string;
                          role?: string | null;
                          photo?: (number | null) | Media;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'organogram';
          }
        | {
            items?:
              | {
                  year: string;
                  title?: string | null;
                  id?: string | null;
                }[]
              | null;
            highlightLast?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            title?: string | null;
            associationsTitle?: string | null;
            partners?:
              | {
                  name: string;
                  logo?: (number | null) | Media;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            associations?:
              | {
                  name: string;
                  logo?: (number | null) | Media;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners';
          }
        | {
            title?: string | null;
            videos?:
              | {
                  title: string;
                  type: 'youtube' | 'internal';
                  src: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoCards';
          }
        | {
            title?: string | null;
            type: 'youtube' | 'internal';
            src: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
        | {
            title?: string | null;
            reports?:
              | {
                  year: string;
                  pdf: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'activityReports';
          }
        | {
            heading: string;
            description?: string | null;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterBlock';
          }
      )[]
    | null;
  /**
   * Content with text, images and mixed custom components
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Title for SEO (if empty, uses the page title)
     */
    metaTitle?: string | null;
    /**
     * Description for search engines
     */
    metaDescription?: string | null;
    /**
     * Image for when the page is shared on social networks
     */
    metaImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses".
 */
export interface Clause {
  id: number;
  number: string;
  title: string;
  date: string;
  version?: string | null;
  pdf?: (number | null) | Media;
  rtf?: (number | null) | Media;
  doc?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the news and press releases displayed on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Automatically generated from the title
   */
  slug: string;
  category: 'actualite' | 'communique' | 'evenement';
  /**
   * Date displayed to the reader. Automatically filled on creation.
   */
  publishedAt: string;
  /**
   * Used on the listing card and at the top of the news.
   */
  featuredImage: number | Media;
  /**
   * Short text
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * If empty, uses the news title.
     */
    metaTitle?: string | null;
    /**
     * If empty, uses the excerpt.
     */
    metaDescription?: string | null;
  };
  /**
   * Date of the last newsletter send for this article.
   */
  newsletterSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage the partners and associations displayed on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  type: 'partner' | 'association';
  /**
   * Partner logo image.
   */
  logo?: (number | null) | Media;
  /**
   * Partner website link (optional).
   */
  href?: string | null;
  /**
   * Display order. Lower number appears first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the videos displayed on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  type: 'youtube' | 'internal';
  /**
   * For YouTube: embed URL (e.g. https://www.youtube.com/embed/ID). For internal: file path (e.g. /videos/my-video.mp4).
   */
  src: string;
  /**
   * Display order. Lower number appears first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the annual activity reports displayed on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-reports".
 */
export interface ActivityReport {
  id: number;
  /**
   * E.g. 2024
   */
  year: string;
  /**
   * Activity report PDF file.
   */
  pdf: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the historical milestones displayed on the homepage timeline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items".
 */
export interface TimelineItem {
  id: number;
  /**
   * E.g. 1990
   */
  year: string;
  /**
   * Event or historical milestone description.
   */
  title: string;
  /**
   * Display order. Lower number appears first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage newsletter subscribers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  status: 'active' | 'unsubscribed';
  /**
   * Auto-generated. Used in the unsubscribe link.
   */
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'activity-reports';
        value: number | ActivityReport;
      } | null)
    | ({
        relationTo: 'timeline-items';
        value: number | TimelineItem;
      } | null)
    | ({
        relationTo: 'clauses';
        value: number | Clause;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  menuOrder?: T;
  icon?: T;
  layout?:
    | T
    | {
        photoHeroCarousel?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    eyebrow?: T;
                    title?: T;
                    id?: T;
                  };
              autoPlayMs?: T;
              id?: T;
              blockName?: T;
            };
        newsSection?:
          | T
          | {
              title?: T;
              maxItems?: T;
              variant?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        documentsSection?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    type?: T;
                    title?: T;
                    triggerLabel?: T;
                    file?: T;
                    videoUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calculator?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        clausesGrid?:
          | T
          | {
              title?: T;
              clauses?: T;
              redirectLabel?: T;
              redirectHref?: T;
              id?: T;
              blockName?: T;
            };
        dynamicGrid?:
          | T
          | {
              title?: T;
              columns?:
                | T
                | {
                    id?: T;
                    label?: T;
                    type?: T;
                    precision?: T;
                    currency?: T;
                  };
              rows?:
                | T
                | {
                    values?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        downloadGrid?:
          | T
          | {
              documents?:
                | T
                | {
                    numero?: T;
                    titulo?: T;
                    data?: T;
                    versao?: T;
                    pdf?: T;
                    rtf?: T;
                    doc?: T;
                    xls?: T;
                    zip?: T;
                    id?: T;
                  };
              pageSize?: T;
              id?: T;
              blockName?: T;
            };
        downloadLinks?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    file?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quickLinks?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    href?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        organogram?:
          | T
          | {
              root?:
                | T
                | {
                    name?: T;
                    role?: T;
                    photo?: T;
                    children?:
                      | T
                      | {
                          name?: T;
                          role?: T;
                          photo?: T;
                          children?:
                            | T
                            | {
                                name?: T;
                                role?: T;
                                photo?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    id?: T;
                  };
              highlightLast?: T;
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              title?: T;
              associationsTitle?: T;
              partners?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    href?: T;
                    id?: T;
                  };
              associations?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoCards?:
          | T
          | {
              title?: T;
              videos?:
                | T
                | {
                    title?: T;
                    type?: T;
                    src?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              title?: T;
              type?: T;
              src?: T;
              id?: T;
              blockName?: T;
            };
        activityReports?:
          | T
          | {
              title?: T;
              reports?:
                | T
                | {
                    year?: T;
                    pdf?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletterBlock?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  newsletterSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  logo?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  src?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-reports_select".
 */
export interface ActivityReportsSelect<T extends boolean = true> {
  year?: T;
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-items_select".
 */
export interface TimelineItemsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses_select".
 */
export interface ClausesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  date?: T;
  version?: T;
  pdf?: T;
  rtf?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}